### PR TITLE
Feature: Support for multiple custom fields

### PR DESCRIPTION
**Pull request by LadySolveig**

### CODE REVIEW

**Comment by nicolaheile** [comment]
That's great, thank you very much! I hope this Feature will be merged. Is it possible to test this feature on my setup? Do I have to build the package on my own?

**Comment by LadySolveig** [comment]
You're welcome, I hope so too. I've only changed two files. For testing purpose you can download them from my repo and replace on your nextcloud instance. 
Files are:
- lib/Controller/PageController 
- lib/Controller/StateController
https://github.com/LadySolveig/Appointments/tree/featmultiple-custom-fields

**Comment by nicolaheile** [comment]
I updated my installation and it does exatcly what I need! Perfect, please merge this feature ;-)

**Comment by Taste-IT** [comment]
I copied both files over existing one, and it doesnt work. I have latest Version 1.11.12, i added {
"tag": "textarea",
"label": "Ihr Anliegen",
"placeholder": "Bitte geben Sie Ihr Anliegen in Stichworten ein"
}
and it didnt work. Can you help?

**Comment by Taste-IT** [comment]
Seems not working in actuell Version of Appointments. I overwrite both files and tested it, with field above - I cant see the field.

**Comment by Taste-IT** [comment]
Thanks for that and is there an possibility to add a checkbox?

**Comment by serotonie** [comment]
Thanks a lot for that, I really hope it could be merge in the futur ! :)

**Comment by iamkhalidbashir** [comment]
Why isnt this merged ?

**Comment by iamkhalidbashir** [comment]
@SergeyMosin Please can we merge this ?

**Comment by nicolaheile** [comment]
Yes, please, I am still waiting for this 🥰

**Pull request merged**
