### PR TITLE
Added display option for 8 and 12 weeks

### PR DESCRIPTION
**Pull request by practical-solutions**
Minor changes to add an option to show the public calendar with slots for the coming 8 or 12 weeks, as we need this possibilty urgently.

### CODE REVIEW

**Comment by nolens** [comment]
@practical-solutions 
Any chance to add 15 and 18 months also? 
I don't know how to do this... Would be awesome!

**Comment by SergeyMosin** [comment]
@practical-solutions Thanks, I'll look into backend implementation but it will have to wait because the right way of doing it would be via lazy loading otherwise parsing 2 months of calendar data at once might slow things down under heavy loads.

> as we need this possibilty urgently

There is a way to modify a variable in DB directly or via occ command if you have access, let me know if you want try.

_P.S. email me at sergey[at ]srgdev.com for a contributor key_

**Comment by nolens** [comment]
@SergeyMosin 
Would love to be able to change "book ahead time" to up to 5 or 6 months.

How do I do this via DB or occ? 

If that is not feasible, how many weeks in advance would you recon are possible, without the lazy load approach that you have mentioned?

**Comment by nolens** [comment]
@SergeyMosin 
Thanks, this helps _me a lot_!

**Pull request merged**
