### PR TITLE
l10n: Adapted strings to Nextcloud universe style

### PR DESCRIPTION
**Pull request by rakekniven**

### CODE REVIEW

**Comment by rakekniven** [comment]
Please see this PR

**Comment by SergeyMosin** [comment]
@rakekniven see commit https://github.com/SergeyMosin/Appointments/commit/e3497dc4c4cb0ef1314b3931a9c946970d810aba, I am leaving "No Appointments Available" as is because each word is displayed on it's own line and the "Book Now" button looks better this way IMHO.
I'll push the changes to the next release once most of the translations are ready.

Thanks

**Comment by rakekniven** [comment]
Would you mind sharing a screenshot?

**Comment by SergeyMosin** [comment]
naa

bn_btn

**Pull request closed without merging**
