### PR TITLE
feat: Pre-Fill input fields given url query parameter

### PR DESCRIPTION
**Pull request by rgon**
This PR implements pre-filling form fields given url query parameters, as requested in #145 

 I have implemented this feature in the formReady method. For ease-of-use, it follows the same standard as cal.com:

> You can add anywhere in the booking flow before the booking form page or in the booking form page itself. Simply add these in the URL and you're good to go!
> https://cal.com/johndoe/book?email=johndoe%40example.com&phone=1234
> Source: https://cal.com/docs/core-features/bookings/prefill-fields#pre-filling-all-fields

It also implements hiding the pre-filled inputs, so that in custom embed flows, we could just iframe the appointments app with the calendar component by setting `hidePrefilledInputs=true`
```
https://mycloud.tld/appointments/appointmentID?name=UserName&email=userEmail&hidePrefilledInputs=true
```

This PR also updates the documentation, referencing this change.

### CODE REVIEW

**Comment by SergeyMosin** [comment]
Thank you. This looks good. We also will need to add a setting for  the users to enable/disable this feature. And maybe an option to display the Pre-Filled data in plain text in addition to `hidePrefilledInputs`

**Comment by rgon** [comment]
Thank you for this project!

I agree that disabling pre-filled values is a good idea. I  have implemented this with the `disablePrefilledInputs` query param and updated this PR:
Screenshot from 2024-08-05 15-15-30

**Comment by rgon** [comment]
Regarding enabling it via the page settings, I have to dig deeper in the code to find out how to implement it. Will update the PR when I figure it out.

**Comment by SergeyMosin** [comment]
> Regarding enabling it via the page settings, I have to dig deeper in the code to find out how to implement it. Will update the PR when I figure it out.

Don't worry about this, I'll add it after merging.

**Pull request merged**
